// Generated by CoffeeScript 1.6.2
(function() {
  var s;

  s = skrollr.init();

  $(function() {
    var $mainNav, $mainNavWrapper;

    $.localScroll();
    $mainNavWrapper = $('#main-nav-wrapper');
    $mainNav = $('#main-nav');
    return $mainNavWrapper.waypoint(function(direction) {
      if (direction === 'down') {
        return $mainNav.addClass('sticky');
      } else {
        return $mainNav.removeClass('sticky');
      }
    });
  });

}).call(this);
